### ISSUE TITLE
Win10下没有 controller

### ISSUE THREAD

**Issue by SkywalkerDarren** [wuyr/intellij-media-player#10]
![image](https://user-images.githubusercontent.com/20706299/123127036-7d690580-d47c-11eb-8512-b35d01f7bb49.png)

可能是因为标题和菜单栏在同一行， 导致视频控制器无法正常展示

**Comment by wuyr** [comment]
是的哈哈，这都被你发现了。
现在打算把controller放到窗口底部了，这样就能兼容各个平台，但是也会占用一点点屏幕空间

**Comment by wuyr** [comment]
已修复，重新下载安装即可
