### ISSUE TITLE
两个大边框

### ISSUE THREAD

**Issue by jingjian3490** [wuyr/intellij-media-player#12]
![image](https://user-images.githubusercontent.com/81038285/123498683-11e18c80-d664-11eb-9de9-94a86d88038c.png)
![image](https://user-images.githubusercontent.com/81038285/123498783-8a484d80-d664-11eb-80da-13ea2b204ba2.png)
更新之后左右两边都有很宽的空白区域，看起来很不舒适，希望可以修复一下。

**Comment by wuyr** [comment]
你的是IDEA吗？播放视频的时候有没有Conctroller在底部显示？

**Comment by jingjian3490** [comment]
> 你是IDEA吗？播放视频的时候有没有控制器在底部显示？
idea 2021.1 ，有显示控制器

**Comment by jingjian3490** [comment]
> 你是IDEA吗？播放视频的时候有没有控制器在底部显示？
idea 2021.1，有显示控制器，可循环播放，win10系统

**Comment by wuyr** [comment]
还是没看出来哪里的空白区域。。。

**Comment by jingjian3490** [comment]
> 还是没看出来哪里的空白区域。。。

![image](https://user-images.githubusercontent.com/81038285/123596106-4dc35000-d824-11eb-894a-82bd6aa76d46.png)


这是我全屏状态下的效果, 左右两边有空白区域, 视频没有占满窗口, 上个版本没有出现这样的情况

**Comment by wuyr** [comment]
噢，这个是按照窗口尺寸自动调整大小了，就是使得视频画面始终能完全在窗口中显示。上一个版本，是会铺满窗口屏幕的，但如果视频跟窗口的宽高比不一样的话，画面就会被拉伸
