### ISSUE TITLE
一个影响不大的小问题

### ISSUE THREAD

**Issue by jingjian3490** [wuyr/intellij-media-player#14]
将idea最小化后视频仍然会播放，能不能设置最小化窗口后停止播放视频

**Comment by wuyr** [comment]
是的，现在设计就是这样的，不会因为最小化而暂停或停止播放

**Comment by Francisonly** [comment]
> 是的，现在设计就是这样的，不会因为最小化而暂停或停止播放

test

**Comment by Francisonly** [comment]
> 将idea最小化后视频仍然会播放，能不能设置最小化窗口后停止播放视频

test

**Comment by Francisonly** [comment]
> > 将idea最小化后视频仍然会播放，能不能设置最小化窗口后停止播放视频
> 
> test

test reply

**Comment by Francisonly** [comment]
> > > 将idea最小化后视频仍然会播放，能不能设置最小化窗口后停止播放视频
> > 
> > 
> > test
> 
> test reply

test.  3
