### ISSUE TITLE
无法播放 选好点击ok直接无法任何反应

### ISSUE THREAD

**Issue by YYJavaGit** [wuyr/intellij-media-player#16]
![image](https://user-images.githubusercontent.com/50813117/124051219-a5dd9a80-da4e-11eb-8f25-aa4343b44be3.png)

IntelliJ IDEA 2021.1.3 (Ultimate Edition)
Build #IU-211.7628.21, built on June 30, 2021

Expiration date: July 31, 2021
Runtime version: 11.0.11+9-b1341.60 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1024M
Cores: 8
Registry: compiler.automake.allow.when.app.running=true, ide.windowSystem.autoShowProcessPopup=true, ide.balloon.shadow.size=0, go.run.processes.with.pty=false, ide.images.show.chessboard=true
Non-Bundled Plugins: Batch Scripts Support (1.0.12), CMD Support (1.0.5), com.biyusheng.plugins (1.3.3), com.github.b3er.idea.plugins.arc.browser (0.23), com.github.redfoos.logstash-intellij-plugin (0.63-EAP), com.jetbrains.ChooseRuntime (1.2), com.wuyr.intellijmediaplayer (1.0), de.netnexus.camelcaseplugin (3.0.8), dev.meanmail.plugin.nginx-intellij-plugin (2021.2-211), io.github.qeesung.component.HighlightBracketPair (1.1.2), io.zhile.research.ide-eval-resetter (2.1.14), net.vektah.codeglance (1.5.4), org.github.erikzielke.gotoproject (1.2), org.jetbrains.plugins.go-template (211.6693.44), com.intellij.kubernetes (211.7142.13), GrepConsole (11.10.211.6086.0), com.alibaba.p3c.smartfox (2.1.0), de.kontext_e.idea.plugins.autofill (1.0), org.intellij.gitee (2021.1.0), io.scheinecker.intellij.coco (1.4.1), MavenRunHelper (4.13.203.000.0), com.ytw88.weappsupport (0.1.0), com.zxy.ijplugin.wechat-miniprogram (3.5.5), com.codota.csp.intellij (4.2.8), org.jetbrains.plugins.node-remote-interpreter (211.6693.65), org.jetbrains.plugins.vue (211.7142.13), org.jetbrains.kotlin (211-1.5.10-release-891-IJ7142.45), com.bruce.intellijplugin.generatesetter (2.7), com.zhaow.restful.toolkit (2.0.9), cn.wuzhizhan.plugin.mybatis (2020.12.18), com.sjhy.plugin.easycode (1.2.4-RC4), com.baomidou.plugin.idea.mybatisx (1.4.16), com.jetbrains.php (211.7142.45), Pythonid (211.7142.45), org.jetbrains.plugins.go (211.7142.36), cn.yiiguxing.plugin.translate (3.1-201)
Kotlin: 211-1.5.10-release-891-IJ7142.45

**Comment by wuyr** [comment]
现在加上了每个步骤的错误提示（之前有一个步骤出错是直接忽略了），重新安装试试
