### ISSUE TITLE
win10 show controller 左下角看不到循环的按钮

### ISSUE THREAD

**Issue by zhangyuLillian** [wuyr/intellij-media-player#18]
win10重新安装插件后，点击show controller左下角看不到循环的按钮

**Comment by Francisonly** [comment]
d

**Comment by Francisonly** [comment]
> win10重新安装插件后，点击show controller左下角看不到循环的按钮

d d

**Comment by Francisonly** [comment]
> d

d d

**Comment by Francisonly** [comment]
> d

g

**Comment by Francisonly** [comment]
> > d
> 
> d d

dd

**Comment by wuyr** [comment]
除了循环的按钮，有看到progressBar和时间戳吗

**Comment by zhangyuLillian** [comment]
> 除了循环的按钮，有看到progressBar和时间戳吗

啥都没有，点了没反应的哪种，你们有的能不能给张截图看看

**Comment by wuyr** [comment]
正常是这样的，看窗口的底部：
![image](https://user-images.githubusercontent.com/9758478/125221620-0e543380-e2fb-11eb-88fb-0fb5df9a31a2.png)
第一个按钮就是循环

**Comment by zhangyuLillian** [comment]
我知道了，是视频太短，来不及点击循环
