### ISSUE TITLE
怎么使用啊

### ISSUE THREAD

**Issue by qktnspsa** [wuyr/intellij-media-player#2]
老哥,,  怎么使用,  在哪里设置视频路径

**Comment by wuyr** [comment]
安装插件并重启之后，在顶部的菜单栏最右边（Help的右边）会看到一个Player的菜单，点击就能打开视频啦。
上周在Mac系统上测试发现会很卡，是屏幕分辨率的问题，这个现在还没有优化，会尽快搞好的。所以如果你的是Mac可能会很卡。。。不过等优化之后就好了

**Comment by qktnspsa** [comment]
老哥.. 6666  已start

**Comment by happyguy1986** [comment]
希望老哥能出更多这样的摸鱼精品

**Comment by wuyr** [comment]
好的，多谢关注
