### ISSUE TITLE
快捷键 alt+x 可以停止播放, 有没有恢复播放的快捷键

### ISSUE THREAD

**Issue by russleung44** [wuyr/intellij-media-player#20]
试过 alt+x 停止之后不能 alt+x 恢复播放, 每次要重新open video比较麻烦

**Comment by wuyr** [comment]
现在没有诶，alt + x是防止领导的快捷键，按下的时候就已经销毁了对应的播放实例了，没有考虑到恢复播放

**Comment by russleung44** [comment]
well
