### ISSUE TITLE
网络地址好像不能用哎

### ISSUE THREAD

**Issue by Nicholas-le** [wuyr/intellij-media-player#3]
![image](https://user-images.githubusercontent.com/61487021/122021776-94628480-cdf8-11eb-9176-e16979d0f6e6.png)

**Comment by wuyr** [comment]
你的是什么系统

**Comment by liudaved** [comment]
遇到过类似的问题, 多重启了几次就正常了

**Comment by lyw1991** [comment]
我也是这个问题，win10

**Comment by wuyr** [comment]
已修复，重新下载即可
