### ISSUE TITLE
win10系统播放视频很卡

### ISSUE THREAD

**Issue by v1huangtengfei** [wuyr/intellij-media-player#6]
win10系统播放视频很卡

**Comment by wuyr** [comment]
是的，上周末在mac（我的是linux）系统上测试也发现有卡顿现象，不过原因已找到，这周内修复。

**Comment by Leothon** [comment]
试了个视频，比PPT稍流畅点，而且电脑风扇呜呜呜响。想到我的macbook光是代码检查都卡，还是算了吧

**Comment by wuyr** [comment]
已修复，重新下载安装即可
